// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PureFood.Data;

#nullable disable

namespace PureFood.Data.Migrations
{
    [DbContext(typeof(PureFoodDbContext))]
    [Migration("20241002154549_DbInit")]
    partial class DbInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "UserId");

                    b.ToTable("AppUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserTokens", (string)null);
                });

            modelBuilder.Entity("PureFood.Core.Domain.Content.Cart", b =>
                {
                    b.Property<Guid>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CartId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("PureFood.Core.Domain.Content.CartItem", b =>
                {
                    b.Property<Guid>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("PureFood.Core.Domain.Content.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("2d482271-9605-4d43-9ca8-d479d6ef9687"),
                            CategoryName = "rau-cu",
                            CreatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rau củ quả ngon lành",
                            UpdatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CategoryId = new Guid("6b5f6458-3791-4303-8ee7-e20707e4cf3e"),
                            CategoryName = "trai-cay",
                            CreatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Trái cây tươi mới",
                            UpdatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PureFood.Core.Domain.Content.Image", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            ImageId = new Guid("2ab8bf12-fe94-4d7a-b5b2-577bca108581"),
                            ProductId = new Guid("0e758eaa-331b-409a-b09a-335cdb16a1f5"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F1.1.jpg?alt=media&token=8aa2db36-a902-45d3-bd89-577a7e1051b9"
                        },
                        new
                        {
                            ImageId = new Guid("5bedca84-0826-4525-8961-3a4b5f3d4488"),
                            ProductId = new Guid("0e758eaa-331b-409a-b09a-335cdb16a1f5"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F1.2.jpg?alt=media&token=5ed9e2ad-a0ab-4144-bb83-b7a0bc943f79"
                        },
                        new
                        {
                            ImageId = new Guid("7417048d-2ac0-456a-b53f-1841f7ab3f56"),
                            ProductId = new Guid("0e758eaa-331b-409a-b09a-335cdb16a1f5"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F1.3.jpg?alt=media&token=85f219cc-ca82-4f76-8813-4b2d01396a54"
                        },
                        new
                        {
                            ImageId = new Guid("ea3b8e36-f677-441e-8c0d-82cb5856fa85"),
                            ProductId = new Guid("0e758eaa-331b-409a-b09a-335cdb16a1f5"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F1.4.jpg?alt=media&token=7cdbdbd1-c9d2-44ea-9472-24a8ad85fc18"
                        },
                        new
                        {
                            ImageId = new Guid("9f082e52-10db-4508-adf9-58f12b3e8c82"),
                            ProductId = new Guid("487ca896-ab72-4735-bee9-1b6a42ec3be6"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F2.1.jpg?alt=media&token=9ebd04cb-02b4-4662-8618-53791f069691"
                        },
                        new
                        {
                            ImageId = new Guid("b68030d5-8fa1-4df6-8193-b92a6f21d14b"),
                            ProductId = new Guid("487ca896-ab72-4735-bee9-1b6a42ec3be6"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F2.2.jpg?alt=media&token=75e12cd9-1e2f-4b83-be28-629f06529e91"
                        },
                        new
                        {
                            ImageId = new Guid("cc0959cf-1c87-4fa5-9554-39e298e71f17"),
                            ProductId = new Guid("487ca896-ab72-4735-bee9-1b6a42ec3be6"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F2.3.jpg?alt=media&token=ffc5cba6-f45f-43d4-a2ae-d181efc60d32"
                        },
                        new
                        {
                            ImageId = new Guid("d5e6cb4e-20c7-4e82-bee8-4142ac208b7a"),
                            ProductId = new Guid("487ca896-ab72-4735-bee9-1b6a42ec3be6"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F2.4.jpg?alt=media&token=b0fa6d72-c3f6-4eb1-a260-00a9e002b6a5"
                        },
                        new
                        {
                            ImageId = new Guid("141b88f2-1fe6-44f9-b9ed-b5230e0948bf"),
                            ProductId = new Guid("30cfb1b3-da69-4a84-b94c-07ffe79597e0"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F3.1.jpg?alt=media&token=d0673683-e125-4784-b417-7d91f36b5487"
                        },
                        new
                        {
                            ImageId = new Guid("2d5909b6-458b-4b15-b6d8-87f5c2698a80"),
                            ProductId = new Guid("30cfb1b3-da69-4a84-b94c-07ffe79597e0"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F3.2.jpg?alt=media&token=768cda30-028d-4750-9b40-fc47b06852f6"
                        },
                        new
                        {
                            ImageId = new Guid("adc3f002-d829-4d0f-9311-5695c3b024cf"),
                            ProductId = new Guid("30cfb1b3-da69-4a84-b94c-07ffe79597e0"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F3.3.jpg?alt=media&token=a6782085-e680-4bd7-98be-4bbbf1755a51"
                        },
                        new
                        {
                            ImageId = new Guid("ebc736a8-05df-41d8-872a-368749bb14b6"),
                            ProductId = new Guid("30cfb1b3-da69-4a84-b94c-07ffe79597e0"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F3.4.jpg?alt=media&token=9b436fa5-ff2a-4bd9-99d1-50cad660d704"
                        },
                        new
                        {
                            ImageId = new Guid("07902c5d-0e3b-4cff-9d74-69ef534d2d94"),
                            ProductId = new Guid("e4cdecb7-84f2-4c28-be13-76b4f771b6f5"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F4.1.jpg?alt=media&token=b769455f-31cb-453f-97ee-b8f4da757cbc"
                        },
                        new
                        {
                            ImageId = new Guid("1b36b25f-9168-4506-8e13-fd62f83acfdc"),
                            ProductId = new Guid("e4cdecb7-84f2-4c28-be13-76b4f771b6f5"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F4.2.jpg?alt=media&token=eaaa7cd4-3448-4d7f-bdef-09a4344cbf27"
                        },
                        new
                        {
                            ImageId = new Guid("3d460368-b879-4cda-991a-5e5c3db5f40e"),
                            ProductId = new Guid("e4cdecb7-84f2-4c28-be13-76b4f771b6f5"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F4.3.jpg?alt=media&token=c2db8a67-158e-4d73-80aa-bcdcca6f1ad9"
                        },
                        new
                        {
                            ImageId = new Guid("bf6af744-6d8f-4ca1-8720-0554a9d11fcb"),
                            ProductId = new Guid("e4cdecb7-84f2-4c28-be13-76b4f771b6f5"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F4.4.jpg?alt=media&token=455b20e2-a6c7-4889-90ef-28f547b08790"
                        },
                        new
                        {
                            ImageId = new Guid("23b8737c-f1db-4148-96c4-2858e8be478b"),
                            ProductId = new Guid("d3fd8b9e-ff11-4c14-a453-edfd58f05135"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F5.1.jpg?alt=media&token=98b82bfa-dc94-4960-b091-fe1307b9ee56"
                        },
                        new
                        {
                            ImageId = new Guid("7124f9ce-7b64-4771-8486-f0cbb389468f"),
                            ProductId = new Guid("d3fd8b9e-ff11-4c14-a453-edfd58f05135"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F5.2.jpg?alt=media&token=4ed5345b-9f3f-4205-a477-8883ccdd5a54"
                        },
                        new
                        {
                            ImageId = new Guid("9a6b98af-6603-4ad6-ae62-b82389c5d8bd"),
                            ProductId = new Guid("d3fd8b9e-ff11-4c14-a453-edfd58f05135"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F5.3.jpg?alt=media&token=9bd2b6a8-8d07-4172-892c-c06b26c661dc"
                        },
                        new
                        {
                            ImageId = new Guid("4c1a249c-a716-4ba3-9647-167c0a2e2d13"),
                            ProductId = new Guid("d3fd8b9e-ff11-4c14-a453-edfd58f05135"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F5.4.jpg?alt=media&token=36b36199-cec7-4421-bb43-1be5d9f90560"
                        },
                        new
                        {
                            ImageId = new Guid("147470fc-0bbd-4e6d-ada8-b616ebffc343"),
                            ProductId = new Guid("6eeb6843-acf8-4760-b1b3-7ff01e5d3e8f"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F6.1.jpg?alt=media&token=62b793d8-c754-461d-ae9c-17ae7986bc06"
                        },
                        new
                        {
                            ImageId = new Guid("3c38777b-ee15-4059-9cd0-b063d5d37a5e"),
                            ProductId = new Guid("6eeb6843-acf8-4760-b1b3-7ff01e5d3e8f"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F6.2.jpg?alt=media&token=6d2437c5-a574-4bc8-9a4a-08c954f66940"
                        },
                        new
                        {
                            ImageId = new Guid("5873d292-a96f-44dc-8eb0-0340fb107c34"),
                            ProductId = new Guid("6eeb6843-acf8-4760-b1b3-7ff01e5d3e8f"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F6.3.jpg?alt=media&token=00501803-2f9e-4d22-9e64-94211c171309"
                        },
                        new
                        {
                            ImageId = new Guid("6ce3b5dc-20ab-48d0-bef1-d8320ffdf317"),
                            ProductId = new Guid("6eeb6843-acf8-4760-b1b3-7ff01e5d3e8f"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F6.5.jpg?alt=media&token=aa7aa923-c490-40fe-82e5-3f6d1103ea6e"
                        },
                        new
                        {
                            ImageId = new Guid("2edd5830-ac8d-4281-9a28-cfc1dd3f159e"),
                            ProductId = new Guid("a5c11a08-497c-4846-b922-bb8a95078dd1"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F7.1.jpg?alt=media&token=b06321a1-6c26-41f9-b707-0b3fddb44fe7"
                        },
                        new
                        {
                            ImageId = new Guid("7ade8654-3f80-45f2-8da9-3dda1e276ec4"),
                            ProductId = new Guid("a5c11a08-497c-4846-b922-bb8a95078dd1"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F7.2.jpg?alt=media&token=7ea8139c-2195-4b99-9b0a-ffc1c34f35ab"
                        },
                        new
                        {
                            ImageId = new Guid("905e459e-99e7-44f7-98a0-cf42c77229f4"),
                            ProductId = new Guid("a5c11a08-497c-4846-b922-bb8a95078dd1"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F7.3.jpg?alt=media&token=7c6000f6-66b6-4020-83f3-089812857d31"
                        },
                        new
                        {
                            ImageId = new Guid("38998549-11cb-4574-ba9c-9c8c91c59c31"),
                            ProductId = new Guid("25134650-be13-43de-bc40-22a9ea54b543"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F8.1.jpg?alt=media&token=1f0a016a-894a-4000-88e3-747adf1142df"
                        },
                        new
                        {
                            ImageId = new Guid("5ac66b04-463e-4fff-a379-a2d5068f516c"),
                            ProductId = new Guid("25134650-be13-43de-bc40-22a9ea54b543"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F8.2.jpg?alt=media&token=0a7802f0-17c9-4e8f-a6f8-38278ad0213d"
                        },
                        new
                        {
                            ImageId = new Guid("6f86b276-f7d6-4b4c-82a0-b5f0afba76ed"),
                            ProductId = new Guid("25134650-be13-43de-bc40-22a9ea54b543"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F8.3.jpg?alt=media&token=9d08e1b6-3feb-4f64-a517-f2550b86d674"
                        },
                        new
                        {
                            ImageId = new Guid("87b04ea4-acbb-48c0-9154-41b58c4c454c"),
                            ProductId = new Guid("25134650-be13-43de-bc40-22a9ea54b543"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F8.4.jpg?alt=media&token=de43b4c1-b3a3-4d88-a61c-3f72ea8ca7dd"
                        },
                        new
                        {
                            ImageId = new Guid("160e7955-47f7-464a-b819-79c47f106b4d"),
                            ProductId = new Guid("8b23df0f-ed33-48c5-9bfa-b2f15a6e6d0f"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F9.1.jpg?alt=media&token=621021f6-6356-458b-bc10-07d85a6096cd"
                        },
                        new
                        {
                            ImageId = new Guid("64fcbca1-fdf4-4e9a-b841-29086da16f36"),
                            ProductId = new Guid("8b23df0f-ed33-48c5-9bfa-b2f15a6e6d0f"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F9.2.jpg?alt=media&token=6648b26a-153e-4bab-a22a-3c58693db145"
                        },
                        new
                        {
                            ImageId = new Guid("80974c62-29d2-4db0-a32e-83ca74cb3383"),
                            ProductId = new Guid("8b23df0f-ed33-48c5-9bfa-b2f15a6e6d0f"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F9.3.jpg?alt=media&token=71642a0b-ade9-45c7-9a4e-0d3bf8aefb08"
                        },
                        new
                        {
                            ImageId = new Guid("c1c1bc06-7d76-4f4b-987d-d4c3efbf5901"),
                            ProductId = new Guid("8b23df0f-ed33-48c5-9bfa-b2f15a6e6d0f"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F9.4.jpg?alt=media&token=0883a03b-33db-45b2-8973-f240e16e9b1b"
                        },
                        new
                        {
                            ImageId = new Guid("1594b568-5855-417d-86cb-96c61c6de1b3"),
                            ProductId = new Guid("8212e748-fe88-40af-894e-708a376f4fa7"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F10.1.jpg?alt=media&token=84e0916e-a3bf-402b-b584-59a96d2ae1b3"
                        },
                        new
                        {
                            ImageId = new Guid("427880a9-3a3e-40c9-96d9-6c64dc6a2b84"),
                            ProductId = new Guid("8212e748-fe88-40af-894e-708a376f4fa7"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F10.2.jpg?alt=media&token=662ba6e6-79ae-4326-9e3b-1f266b06141e"
                        },
                        new
                        {
                            ImageId = new Guid("56391da7-a3f5-4c8e-a5f6-f57abcf7f3e6"),
                            ProductId = new Guid("8212e748-fe88-40af-894e-708a376f4fa7"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F10.3.jpg?alt=media&token=5f1f19a4-1480-4ffe-8c54-c498342ff817"
                        },
                        new
                        {
                            ImageId = new Guid("0058660f-548f-4a05-9985-35adf77fa17b"),
                            ProductId = new Guid("6404ba59-9c63-4192-889b-3448cd7c9ba0"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F11.1.jpg?alt=media&token=0269ab46-401e-4f16-b189-cad618ac7017"
                        },
                        new
                        {
                            ImageId = new Guid("9856e332-caf4-406e-9ac4-647eaa797a74"),
                            ProductId = new Guid("6404ba59-9c63-4192-889b-3448cd7c9ba0"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F11.2.jpg?alt=media&token=0721c18d-3b51-4266-89ac-c5c7442bc59c"
                        },
                        new
                        {
                            ImageId = new Guid("fe925dc4-bbd5-4d5d-a13b-1f3a6ee6628e"),
                            ProductId = new Guid("6404ba59-9c63-4192-889b-3448cd7c9ba0"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F11.3.jpg?alt=media&token=9b3e318d-63e3-47ec-968f-8bd053f1fc15"
                        },
                        new
                        {
                            ImageId = new Guid("0c4ba54d-a39a-4c1b-bbb8-c909362fe973"),
                            ProductId = new Guid("7a684d3b-8e9f-4f06-a767-d59c1953f249"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F12.1.jpg?alt=media&token=e7794ede-ec4e-411e-a5f3-23bf37bd8c76"
                        },
                        new
                        {
                            ImageId = new Guid("29f8c2c4-222c-4c41-adda-5d74e281e6dd"),
                            ProductId = new Guid("7a684d3b-8e9f-4f06-a767-d59c1953f249"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F12.2.jpg?alt=media&token=cdc9fd2b-3d64-4242-bc3a-353f5558d8d1"
                        },
                        new
                        {
                            ImageId = new Guid("3416a262-1421-4199-b15d-7c425d68f0ae"),
                            ProductId = new Guid("7a684d3b-8e9f-4f06-a767-d59c1953f249"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F12.3.jpg?alt=media&token=f86f1e73-dbdd-4358-8308-d3143655ae2f"
                        },
                        new
                        {
                            ImageId = new Guid("68f9bd1e-fd66-45fb-8c7c-41cb7c3a69e9"),
                            ProductId = new Guid("74bc7dde-d01e-46ca-8fa6-e7cb7a70bb31"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F13.1.jpg?alt=media&token=38cb92b8-6399-40df-9865-ee7eeae02616"
                        },
                        new
                        {
                            ImageId = new Guid("74a5cdda-708a-4be2-8507-5f2f00c42883"),
                            ProductId = new Guid("74bc7dde-d01e-46ca-8fa6-e7cb7a70bb31"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F13.5.jpg?alt=media&token=5c80780a-68ac-44ec-b369-80b5b92f9ef5"
                        },
                        new
                        {
                            ImageId = new Guid("fb4ca598-f62a-419e-a94d-7f03d30944fb"),
                            ProductId = new Guid("74bc7dde-d01e-46ca-8fa6-e7cb7a70bb31"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F13.4.jpg?alt=media&token=eb410528-7cac-4971-a0b1-02da1096b227"
                        },
                        new
                        {
                            ImageId = new Guid("113eea99-b426-447c-a608-aaa3f7be7267"),
                            ProductId = new Guid("2adef94c-fa06-4369-89ab-34e71052368e"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F14.1.jpg?alt=media&token=45bdde25-32ac-4807-9342-6c11487c11a4"
                        },
                        new
                        {
                            ImageId = new Guid("3305f179-86ef-45c5-b323-f058e1cef81d"),
                            ProductId = new Guid("2adef94c-fa06-4369-89ab-34e71052368e"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F14.2.jpg?alt=media&token=10434244-5b92-4216-9e1a-8929b8a1c1f4"
                        },
                        new
                        {
                            ImageId = new Guid("7108b731-0a30-4be6-a1c1-ae5e72ba0d3a"),
                            ProductId = new Guid("2adef94c-fa06-4369-89ab-34e71052368e"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F14.3.jpg?alt=media&token=e0274537-66f5-43dd-8fea-58da0741f760"
                        },
                        new
                        {
                            ImageId = new Guid("0fc41889-3ff8-452b-8b98-e36f80d04360"),
                            ProductId = new Guid("6b821109-b650-4fa6-be2a-36dc8d5fbb4d"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F15.1.jpg?alt=media&token=be4b11c9-8d18-4095-a526-3502120db66a"
                        },
                        new
                        {
                            ImageId = new Guid("23f35439-253a-49be-9beb-486c8be37c90"),
                            ProductId = new Guid("6b821109-b650-4fa6-be2a-36dc8d5fbb4d"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F15.2.jpg?alt=media&token=47cd5fb6-5261-43ed-9471-6583899e2933"
                        },
                        new
                        {
                            ImageId = new Guid("81d44c50-ade1-4913-899d-8ab35f14fe1c"),
                            ProductId = new Guid("6b821109-b650-4fa6-be2a-36dc8d5fbb4d"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F15.4.jpg?alt=media&token=639dec84-1a77-4acf-ac8d-bbe45c7c0ec1"
                        },
                        new
                        {
                            ImageId = new Guid("09a63769-85fe-4b22-972c-36d809084a5e"),
                            ProductId = new Guid("fc727800-963c-4305-93a0-3b27dfb1d734"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F16.1.jpeg?alt=media&token=240f0de8-7539-4c58-8009-275016b88a46"
                        },
                        new
                        {
                            ImageId = new Guid("870d103c-6a41-4037-8512-a50552570ae5"),
                            ProductId = new Guid("fc727800-963c-4305-93a0-3b27dfb1d734"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F16.2.jpeg?alt=media&token=373fbcd2-ae1f-4edb-951d-050edf0fddce"
                        },
                        new
                        {
                            ImageId = new Guid("eb5ee868-c10f-4afe-8606-91f1752e8b26"),
                            ProductId = new Guid("fc727800-963c-4305-93a0-3b27dfb1d734"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F16.3.jpeg?alt=media&token=973e8efd-51e9-483d-9d87-2498bf0c3240"
                        },
                        new
                        {
                            ImageId = new Guid("fe6aeb73-17cc-4d83-91fe-7b009ceb0091"),
                            ProductId = new Guid("fc727800-963c-4305-93a0-3b27dfb1d734"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F16.4.jpeg?alt=media&token=0ad2cedb-da0e-45d0-85f2-e01def24e449"
                        },
                        new
                        {
                            ImageId = new Guid("0e853075-8de3-40ab-afa6-5c7246118a47"),
                            ProductId = new Guid("ba9968e6-4ad4-406c-9268-28acd686f73c"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F17.1.jpg?alt=media&token=1db77c6c-68a5-4908-9391-c88f44688ae8"
                        },
                        new
                        {
                            ImageId = new Guid("3e68861e-8ca4-4821-b145-de55067335d4"),
                            ProductId = new Guid("ba9968e6-4ad4-406c-9268-28acd686f73c"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F17.2.jpg?alt=media&token=f2f3d557-46fd-4f54-82b3-17077ab6cca5"
                        },
                        new
                        {
                            ImageId = new Guid("52b1b4ac-f0c1-406e-b30f-7b1981327327"),
                            ProductId = new Guid("ba9968e6-4ad4-406c-9268-28acd686f73c"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F17.3.jpg?alt=media&token=0646948b-03c0-4417-8327-be728a121e63"
                        },
                        new
                        {
                            ImageId = new Guid("ed53b62e-1a70-4a11-bba8-efe527a63f47"),
                            ProductId = new Guid("ba9968e6-4ad4-406c-9268-28acd686f73c"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F17.4.jpg?alt=media&token=7e88e4c0-3b8e-4749-aa0a-f69d53e24f69"
                        },
                        new
                        {
                            ImageId = new Guid("1d74d733-8b94-4043-b2e6-717bc76bd604"),
                            ProductId = new Guid("576aa3a9-49ff-486c-8efc-a0548ee90ee7"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F18.1.jpg?alt=media&token=b05ea5eb-c364-4017-9727-b29a9ba39139"
                        },
                        new
                        {
                            ImageId = new Guid("2416f0a9-bc9e-4ced-a425-af1481ca8c0b"),
                            ProductId = new Guid("576aa3a9-49ff-486c-8efc-a0548ee90ee7"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F18.2.jpg?alt=media&token=f41c8267-27a0-46a1-ac00-183aa7bc303e"
                        },
                        new
                        {
                            ImageId = new Guid("9b59ee88-21f1-44ac-ad0a-d843ed7802c5"),
                            ProductId = new Guid("576aa3a9-49ff-486c-8efc-a0548ee90ee7"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F18.3.jpg?alt=media&token=d61ca12f-1e94-4b50-a420-a4a83e0ccfc1"
                        },
                        new
                        {
                            ImageId = new Guid("e7556fef-42a8-4494-bdd5-bc39a7cce1aa"),
                            ProductId = new Guid("576aa3a9-49ff-486c-8efc-a0548ee90ee7"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F18.4.jpg?alt=media&token=f9bddef4-1395-485e-9513-445289e0ef74"
                        },
                        new
                        {
                            ImageId = new Guid("250b5b32-9197-45dd-a85d-f21d5c922737"),
                            ProductId = new Guid("a69cd06b-8762-49cc-9228-1fc88956fb3c"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F19.1.jpg?alt=media&token=ecfdf322-bb3d-4959-ac7d-36ee2ca2ca98"
                        },
                        new
                        {
                            ImageId = new Guid("afd40e26-3e41-421d-8b74-fd35ff43cade"),
                            ProductId = new Guid("a69cd06b-8762-49cc-9228-1fc88956fb3c"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F19.2.jpg?alt=media&token=5aec55ad-ad90-448b-9ae6-38c2181a7a28"
                        },
                        new
                        {
                            ImageId = new Guid("dc1d2736-c849-4d4c-9817-6f19031c0b16"),
                            ProductId = new Guid("a69cd06b-8762-49cc-9228-1fc88956fb3c"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F19.3.jpg?alt=media&token=404b341d-64f9-4ca5-a5d5-cae220042c5e"
                        },
                        new
                        {
                            ImageId = new Guid("43f77651-ab4f-4af9-8f58-be8d2790aa15"),
                            ProductId = new Guid("b39c0722-44aa-49e5-8ff9-b9ad9a9594fc"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F20.1.jpg?alt=media&token=2db339d6-5004-4dce-ab54-9b2377bff2a6"
                        },
                        new
                        {
                            ImageId = new Guid("6e35ff78-1205-4164-bf2e-2d91af27f405"),
                            ProductId = new Guid("b39c0722-44aa-49e5-8ff9-b9ad9a9594fc"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F20.2.jpg?alt=media&token=516e44b7-6f8b-4db7-a610-0a3eeb063745"
                        },
                        new
                        {
                            ImageId = new Guid("df705ccd-c062-45df-ac5e-49bedb874971"),
                            ProductId = new Guid("b39c0722-44aa-49e5-8ff9-b9ad9a9594fc"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F20.3.jpg?alt=media&token=ecdffbec-29d1-4f1d-9ddf-616f92a3b15d"
                        },
                        new
                        {
                            ImageId = new Guid("fd927a8e-a6f5-4d22-b593-e9aec49d6fd7"),
                            ProductId = new Guid("b39c0722-44aa-49e5-8ff9-b9ad9a9594fc"),
                            Url = "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/PureFood%2FProductEx%2F20.4.jpg?alt=media&token=0fb153d2-b1b5-4ae7-a823-f802cd9bc952"
                        });
                });

            modelBuilder.Entity("PureFood.Core.Domain.Content.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Commune")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PureFood.Core.Domain.Content.OrderItem", b =>
                {
                    b.Property<Guid>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("PureFood.Core.Domain.Content.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Organic")
                        .HasColumnType("bit");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("0e758eaa-331b-409a-b09a-335cdb16a1f5"),
                            CategoryId = new Guid("2d482271-9605-4d43-9ca8-d479d6ef9687"),
                            CreatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Rau muống tươi ngon, giàu chất xơ, sản phẩm sạch từ nông trại, có nhiều giá trị dinh dưỡng.</p><br>   <ul><br>      <li>Giàu chất xơ, tốt cho hệ tiêu hóa</li><br>      <li>Giàu vitamin A và C</li><br>      <li>Không thuốc bảo vệ thực vật</li><br>      <li>Thích hợp chế biến các món xào, nấu canh</li><br>      <li>Được trồng tại các nông trại xanh</li><br>    </ul>",
                            EntryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodName = "Water spinach",
                            Organic = true,
                            Origin = "Tỉnh Long An",
                            Price = 8000m,
                            ProductName = "Rau muống",
                            Slug = "rau-muong-400-gr-zk7dwx",
                            Status = true,
                            Stock = 100,
                            SupplierId = new Guid("5a0b659d-884a-446a-8b77-9b84ed6e2bf2"),
                            Unit = "Gr",
                            UpdatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 400.0
                        },
                        new
                        {
                            ProductId = new Guid("487ca896-ab72-4735-bee9-1b6a42ec3be6"),
                            CategoryId = new Guid("2d482271-9605-4d43-9ca8-d479d6ef9687"),
                            CreatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Bắp cải tươi ngon, giòn ngọt, sản phẩm hữu cơ giàu vitamin và chất xơ.</p><br><ul><br>  <li>Giàu vitamin K và C, tốt cho sức khỏe xương và hệ miễn dịch</li><br>  <li>Hàm lượng chất chống oxy hóa cao</li><br> <li>Không sử dụng thuốc trừ sâu</li><br>  <li>Thích hợp chế biến món luộc, xào và salad</li><br>  <li>Trồng tại các nông trại hữu cơ</li><br></ul>",
                            EntryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodName = "Cabbage",
                            Organic = true,
                            Origin = "Tỉnh Lâm Đồng",
                            Price = 12500m,
                            ProductName = "Bắp cải",
                            Slug = "bap-cai-500-gr-rkwi1a",
                            Status = true,
                            Stock = 100,
                            SupplierId = new Guid("5a0b659d-884a-446a-8b77-9b84ed6e2bf2"),
                            Unit = "Gr",
                            UpdatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 500.0
                        },
                        new
                        {
                            ProductId = new Guid("30cfb1b3-da69-4a84-b94c-07ffe79597e0"),
                            CategoryId = new Guid("2d482271-9605-4d43-9ca8-d479d6ef9687"),
                            CreatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Giá sống tươi mát, giàu dinh dưỡng, sản phẩm sạch từ nông trại.</p><br><ul><br>  <li>Giàu chất xơ và vitamin E</li><br>  <li>Tốt cho hệ tiêu hóa và làn da</li><br>  <li>Không thuốc bảo vệ thực vật</li><br>  <li>Dùng trong các món gỏi, xào, và phở</li><br>  <li>Được trồng tại các nông trại xanh</li><br></ul>",
                            EntryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodName = "Bean sprouts",
                            Organic = true,
                            Origin = "Tỉnh Tiền Giang",
                            Price = 6800m,
                            ProductName = "Giá sống",
                            Slug = "gia-song-200-gr-fb1ihn",
                            Status = true,
                            Stock = 100,
                            SupplierId = new Guid("5a0b659d-884a-446a-8b77-9b84ed6e2bf2"),
                            Unit = "Gr",
                            UpdatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 200.0
                        },
                        new
                        {
                            ProductId = new Guid("e4cdecb7-84f2-4c28-be13-76b4f771b6f5"),
                            CategoryId = new Guid("2d482271-9605-4d43-9ca8-d479d6ef9687"),
                            CreatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Nấm kim châm tươi ngon, giàu protein và vitamin, sản phẩm sạch từ nông trại.</p><br><ul><br>  <li>Giàu protein, tốt cho sức khỏe tổng thể</li><br>  <li>Chứa nhiều vitamin B và chất chống oxy hóa</li><br>  <li>Không chứa chất hóa học</li><br>  <li>Thích hợp dùng trong lẩu, xào, và món súp</li><br> <li>Trồng tại các nông trại sạch</li><br></ul>",
                            EntryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodName = "Enoki mushrooms",
                            Organic = true,
                            Origin = "Thành phố Hồ Chí Minh",
                            Price = 11000m,
                            ProductName = "Nấm kim châm",
                            Slug = "nam-kim-cham-150-gr-edwynx",
                            Status = true,
                            Stock = 100,
                            SupplierId = new Guid("5a0b659d-884a-446a-8b77-9b84ed6e2bf2"),
                            Unit = "Gr",
                            UpdatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 150.0
                        },
                        new
                        {
                            ProductId = new Guid("d3fd8b9e-ff11-4c14-a453-edfd58f05135"),
                            CategoryId = new Guid("2d482271-9605-4d43-9ca8-d479d6ef9687"),
                            CreatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Cà rốt tươi ngon, ngọt lành, giàu vitamin A và chất chống oxy hóa.</p><br><ul><br>  <li>Giàu vitamin A, tốt cho mắt</li><br>  <li>Hàm lượng chất chống oxy hóa cao</li><br>  <li>Không dùng hóa chất bảo vệ thực vật</li><br>  <li>Thích hợp cho món nước ép, nấu canh và xào</li><br>  <li>Được trồng tại nông trại hữu cơ</li><br></ul>",
                            EntryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodName = "Carrot",
                            Organic = true,
                            Origin = "Tỉnh Lâm Đồng",
                            Price = 11500m,
                            ProductName = "Cà rốt",
                            Slug = "ca-rot-500-gr-xhj7ec",
                            Status = true,
                            Stock = 100,
                            SupplierId = new Guid("5a0b659d-884a-446a-8b77-9b84ed6e2bf2"),
                            Unit = "Gr",
                            UpdatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 500.0
                        },
                        new
                        {
                            ProductId = new Guid("6eeb6843-acf8-4760-b1b3-7ff01e5d3e8f"),
                            CategoryId = new Guid("2d482271-9605-4d43-9ca8-d479d6ef9687"),
                            CreatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Củ dền tươi, giàu vitamin và khoáng chất, thích hợp cho các món ăn bổ dưỡng.</p><br><ul><br>  <li>Giàu folate và chất sắt, tốt cho máu</li><br>  <li>Chứa nhiều chất chống oxy hóa</li><br>  <li>Không thuốc bảo vệ thực vật</li><br>  <li>Thích hợp cho nước ép, nấu canh và salad</li><br>  <li>Trồng tại các nông trại hữu cơ</li><br></ul>",
                            EntryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodName = "Beetroot",
                            Organic = true,
                            Origin = "Tỉnh Lâm Đồng",
                            Price = 22500m,
                            ProductName = "Củ dền",
                            Slug = "cu-den-500-gr-wxels8",
                            Status = true,
                            Stock = 100,
                            SupplierId = new Guid("5a0b659d-884a-446a-8b77-9b84ed6e2bf2"),
                            Unit = "Gr",
                            UpdatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 500.0
                        },
                        new
                        {
                            ProductId = new Guid("a5c11a08-497c-4846-b922-bb8a95078dd1"),
                            CategoryId = new Guid("2d482271-9605-4d43-9ca8-d479d6ef9687"),
                            CreatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Hành tím tươi, vị thơm nồng, giàu dinh dưỡng, sản phẩm sạch từ nông trại.</p><br><ul><br>  <li>Giàu vitamin C và chất xơ</li><br>  <li>Có tính kháng viêm tự nhiên</li><br> <li>Không dùng hóa chất bảo vệ thực vật</li><br>  <li>Thích hợp làm gia vị trong nhiều món ăn</li><br>  <li>Được trồng tại nông trại sạch</li><br></ul>",
                            EntryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodName = "Red onion",
                            Organic = true,
                            Origin = "Tỉnh Sóc Trăng",
                            Price = 15000m,
                            ProductName = "Hành tím",
                            Slug = "hanh-tim-200-gr-aw4230",
                            Status = true,
                            Stock = 100,
                            SupplierId = new Guid("5a0b659d-884a-446a-8b77-9b84ed6e2bf2"),
                            Unit = "Gr",
                            UpdatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 200.0
                        },
                        new
                        {
                            ProductId = new Guid("25134650-be13-43de-bc40-22a9ea54b543"),
                            CategoryId = new Guid("2d482271-9605-4d43-9ca8-d479d6ef9687"),
                            CreatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Hành tây tươi, giòn ngọt, giàu vitamin và khoáng chất, thích hợp cho nhiều món ăn.</p><br><ul><br>  <li>Giàu vitamin C và chất chống oxy hóa</li>\r\n  <li>Có tác dụng kháng viêm, tốt cho sức khỏe</li><br>  <li>Không thuốc trừ sâu</li><br>  <li>Thích hợp nấu canh, xào và làm salad</li><br>  <li>Trồng tại các nông trại hữu cơ</li><br></ul>",
                            EntryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodName = "Onion",
                            Organic = true,
                            Origin = "Tỉnh Lâm Đồng",
                            Price = 8750m,
                            ProductName = "Hành tây",
                            Slug = "hanh-tay-500-gr-xowt5w",
                            Status = true,
                            Stock = 100,
                            SupplierId = new Guid("5a0b659d-884a-446a-8b77-9b84ed6e2bf2"),
                            Unit = "Gr",
                            UpdatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 500.0
                        },
                        new
                        {
                            ProductId = new Guid("8b23df0f-ed33-48c5-9bfa-b2f15a6e6d0f"),
                            CategoryId = new Guid("2d482271-9605-4d43-9ca8-d479d6ef9687"),
                            CreatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Tỏi tươi, vị cay nồng, giàu chất chống oxy hóa, sản phẩm sạch từ nông trại.</p><br><ul><br>  <li>Giàu chất chống oxy hóa và kháng khuẩn</li><br>  <li>Giúp tăng cường hệ miễn dịch</li><br>  <li>Không thuốc bảo vệ thực vật</li><br>  <li>Thích hợp làm gia vị trong các món ăn</li><br>  <li>Trồng tại các nông trại sạch</li><br></ul>",
                            EntryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodName = "Garlic",
                            Organic = true,
                            Origin = "Tỉnh Kiên Giang",
                            Price = 32000m,
                            ProductName = "Tỏi cô đơn",
                            Slug = "toi-co-don-200-gr-9rmr8t",
                            Status = true,
                            Stock = 100,
                            SupplierId = new Guid("5a0b659d-884a-446a-8b77-9b84ed6e2bf2"),
                            Unit = "Gr",
                            UpdatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 200.0
                        },
                        new
                        {
                            ProductId = new Guid("8212e748-fe88-40af-894e-708a376f4fa7"),
                            CategoryId = new Guid("2d482271-9605-4d43-9ca8-d479d6ef9687"),
                            CreatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Khoai môn tươi ngon, giàu dinh dưỡng, sản phẩm sạch từ nông trại.</p><br><ul>\r\n  <li>Giàu chất xơ và vitamin B6</li><br>  <li>Tốt cho hệ tiêu hóa và tim mạch</li><br>  <li>Không dùng hóa chất bảo vệ thực vật</li><br>  <li>Thích hợp cho các món nấu, chiên, và hầm</li><br>  <li>Được trồng tại các nông trại hữu cơ</li><br></ul>",
                            EntryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodName = "Taro",
                            Organic = true,
                            Origin = "Thành phố Bạc Liêu",
                            Price = 26000m,
                            ProductName = "Khoai môn",
                            Slug = "khoai-mon-500-gr-8q8nq9",
                            Status = true,
                            Stock = 100,
                            SupplierId = new Guid("5a0b659d-884a-446a-8b77-9b84ed6e2bf2"),
                            Unit = "Gr",
                            UpdatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 500.0
                        },
                        new
                        {
                            ProductId = new Guid("6404ba59-9c63-4192-889b-3448cd7c9ba0"),
                            CategoryId = new Guid("2d482271-9605-4d43-9ca8-d479d6ef9687"),
                            CreatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Khoai tây tươi, giàu dinh dưỡng, thích hợp cho nhiều món ăn.</p><br><ul><br>  <li>Giàu vitamin C và chất xơ</li><br>  <li>Hàm lượng chất chống oxy hóa cao</li><br>  <li>Không thuốc bảo vệ thực vật</li><br>  <li>Thích hợp cho các món chiên, nướng, và hầm</li><br>  <li>Được trồng tại nông trại sạch</li><br></ul>",
                            EntryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodName = "Potato",
                            Organic = true,
                            Origin = "Tỉnh Lâm Đồng",
                            Price = 30000m,
                            ProductName = "Khoai tây",
                            Slug = "khoai-tay-1-kg-0sls2y",
                            Status = true,
                            Stock = 100,
                            SupplierId = new Guid("5a0b659d-884a-446a-8b77-9b84ed6e2bf2"),
                            Unit = "Kg",
                            UpdatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 1.0
                        },
                        new
                        {
                            ProductId = new Guid("7a684d3b-8e9f-4f06-a767-d59c1953f249"),
                            CategoryId = new Guid("2d482271-9605-4d43-9ca8-d479d6ef9687"),
                            CreatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Khoai lang ngọt lành, giàu dinh dưỡng, sản phẩm sạch từ nông trại.</p><br><ul>\r\n  <li>Giàu vitamin A và chất xơ</li>\r\n  <li>Tốt cho hệ tiêu hóa và sức khỏe mắt</li>\r\n  <li>Không dùng hóa chất bảo vệ thực vật</li><br>  <li>Thích hợp nướng, luộc và làm súp</li><br>  <li>Được trồng tại nông trại hữu cơ</li><br></ul>",
                            EntryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodName = "Sweet potato",
                            Organic = true,
                            Origin = "Thành phố Vĩnh Long",
                            Price = 34000m,
                            ProductName = "Khoai lang",
                            Slug = "khoai-lang-1-kg-hu8kgx",
                            Status = true,
                            Stock = 100,
                            SupplierId = new Guid("5a0b659d-884a-446a-8b77-9b84ed6e2bf2"),
                            Unit = "Kg",
                            UpdatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 1.0
                        },
                        new
                        {
                            ProductId = new Guid("74bc7dde-d01e-46ca-8fa6-e7cb7a70bb31"),
                            CategoryId = new Guid("2d482271-9605-4d43-9ca8-d479d6ef9687"),
                            CreatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Gừng tươi, thơm nồng, giàu chất chống oxy hóa, sản phẩm sạch từ nông trại.</p><br><ul><br>  <li>Giàu chất chống viêm và kháng khuẩn</li><br>  <li>Giúp tăng cường hệ miễn dịch và hỗ trợ tiêu hóa</li><br>  <li>Không thuốc bảo vệ thực vật</li><br>  <li>Thích hợp làm gia vị cho nhiều món ăn</li><br>  <li>Được trồng tại nông trại hữu cơ</li><br></ul>",
                            EntryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodName = "Ginger",
                            Organic = true,
                            Origin = "Tỉnh Lâm Đồng",
                            Price = 4250m,
                            ProductName = "Gừng",
                            Slug = "gung-50-gr-vc4465",
                            Status = true,
                            Stock = 100,
                            SupplierId = new Guid("5a0b659d-884a-446a-8b77-9b84ed6e2bf2"),
                            Unit = "Kg",
                            UpdatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 50.0
                        },
                        new
                        {
                            ProductId = new Guid("2adef94c-fa06-4369-89ab-34e71052368e"),
                            CategoryId = new Guid("2d482271-9605-4d43-9ca8-d479d6ef9687"),
                            CreatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Củ cải trắng tươi ngon, giòn ngọt, giàu vitamin và khoáng chất.</p><br><ul><br>  <li>Giàu vitamin C, tốt cho sức khỏe tổng thể</li><br>  <li>Chứa nhiều chất chống oxy hóa</li><br>  <li>Không thuốc bảo vệ thực vật</li><br>  <li>Thích hợp làm nộm, nấu canh và xào</li><br>  <li>Trồng tại các nông trại sạch</li><br></ul>",
                            EntryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodName = "Daikon radish",
                            Organic = true,
                            Origin = "Tỉnh Lâm Đồng",
                            Price = 10450m,
                            ProductName = "Củ cải trắng",
                            Slug = "cu-cai-trang-500-gr-8irui7",
                            Status = true,
                            Stock = 100,
                            SupplierId = new Guid("5a0b659d-884a-446a-8b77-9b84ed6e2bf2"),
                            Unit = "Gr",
                            UpdatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 500.0
                        },
                        new
                        {
                            ProductId = new Guid("6b821109-b650-4fa6-be2a-36dc8d5fbb4d"),
                            CategoryId = new Guid("2d482271-9605-4d43-9ca8-d479d6ef9687"),
                            CreatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Củ sắn tươi, ngọt lành, giàu dinh dưỡng, sản phẩm sạch từ nông trại.</p>\r\n<ul>\r\n  <li>Giàu vitamin C và chất xơ</li><br>  <li>Tốt cho hệ tiêu hóa</li><br>  <li>Không thuốc bảo vệ thực vật</li><br>  <li>Thích hợp nấu canh, xào và làm salad</li><br>  <li>Được trồng tại nông trại hữu cơ</li><br></ul>",
                            EntryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodName = "Jicama",
                            Organic = true,
                            Origin = "Thành phố Tây Ninh",
                            Price = 11500m,
                            ProductName = "Củ sắn",
                            Slug = "cu-san-500-gr-uv72km",
                            Status = true,
                            Stock = 100,
                            SupplierId = new Guid("5a0b659d-884a-446a-8b77-9b84ed6e2bf2"),
                            Unit = "Gr",
                            UpdatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 500.0
                        },
                        new
                        {
                            ProductId = new Guid("fc727800-963c-4305-93a0-3b27dfb1d734"),
                            CategoryId = new Guid("2d482271-9605-4d43-9ca8-d479d6ef9687"),
                            CreatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Bơ Booth tươi ngon, giàu dinh dưỡng, chứa nhiều chất béo lành mạnh.</p><br><ul><br>  <li>Giàu chất béo không bão hòa, tốt cho tim mạch</li><br>  <li>Chứa nhiều vitamin E và chất xơ</li><br>  <li>Không hóa chất bảo quản</li><br>  <li>Thích hợp làm sinh tố, salad và ăn trực tiếp</li><br>  <li>Trồng tại các nông trại hữu cơ</li><br></ul>",
                            EntryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodName = "Avocado",
                            Organic = true,
                            Origin = "Tỉnh Lâm Đồng",
                            Price = 26000m,
                            ProductName = "Bơ Booth",
                            Slug = "bo-booth-1-kg-n0390m",
                            Status = true,
                            Stock = 100,
                            SupplierId = new Guid("5a0b659d-884a-446a-8b77-9b84ed6e2bf2"),
                            Unit = "Kg",
                            UpdatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 1.0
                        },
                        new
                        {
                            ProductId = new Guid("ba9968e6-4ad4-406c-9268-28acd686f73c"),
                            CategoryId = new Guid("2d482271-9605-4d43-9ca8-d479d6ef9687"),
                            CreatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Hành lá tươi, xanh non, giàu vitamin và khoáng chất, sản phẩm sạch từ nông trại.</p><br><ul><br> <li>Giàu vitamin A và C</li><br>  <li>Tốt cho sức khỏe mắt và hệ miễn dịch</li><br>  <li>Không thuốc bảo vệ thực vật</li><br>  <li>Thích hợp làm gia vị cho nhiều món ăn</li><br> <li>Trồng tại các nông trại xanh</li><br></ul>",
                            EntryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodName = "Green onion",
                            Organic = true,
                            Origin = "Thành phố Hồ Chí Minh",
                            Price = 7900m,
                            ProductName = "Hành lá",
                            Slug = "hanh-la-100-gr-hx03dw",
                            Status = true,
                            Stock = 100,
                            SupplierId = new Guid("5a0b659d-884a-446a-8b77-9b84ed6e2bf2"),
                            Unit = "Kg",
                            UpdatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 100.0
                        },
                        new
                        {
                            ProductId = new Guid("576aa3a9-49ff-486c-8efc-a0548ee90ee7"),
                            CategoryId = new Guid("2d482271-9605-4d43-9ca8-d479d6ef9687"),
                            CreatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Dưa hấu ngọt mát, tươi ngon, sản phẩm sạch từ nông trại.</p><br><ul><br>  <li>Giàu nước, giúp giải khát hiệu quả</li><br>  <li>Chứa nhiều vitamin A và C</li><br> <li>Không hóa chất bảo quản</li><br>  <li>Thích hợp ăn trực tiếp và làm nước ép</li>\r\n  <li>Trồng tại các nông trại hữu cơ</li><br></ul>",
                            EntryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodName = "Melon",
                            Organic = true,
                            Origin = "Tỉnh Long An",
                            Price = 35400m,
                            ProductName = "Dưa hấu",
                            Slug = "dua-hau-2-kg-im862u",
                            Status = true,
                            Stock = 100,
                            SupplierId = new Guid("5a0b659d-884a-446a-8b77-9b84ed6e2bf2"),
                            Unit = "Kg",
                            UpdatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 2.0
                        },
                        new
                        {
                            ProductId = new Guid("a69cd06b-8762-49cc-9228-1fc88956fb3c"),
                            CategoryId = new Guid("2d482271-9605-4d43-9ca8-d479d6ef9687"),
                            CreatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Dưa lưới tươi ngon, ngọt mát, giàu dinh dưỡng, sản phẩm sạch từ nông trại.</p><br><ul><br>  <li>Giàu vitamin A và C, tốt cho sức khỏe</li><br>  <li>Chứa nhiều nước, giúp giải khát</li><br>  <li>Không dùng hóa chất bảo quản</li><br>  <li>Thích hợp ăn trực tiếp và làm sinh tố</li><br>  <li>Trồng tại các nông trại xanh</li><br></ul>",
                            EntryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodName = "Melon",
                            Organic = true,
                            Origin = "Tỉnh Tiền Giang",
                            Price = 38000m,
                            ProductName = "Dưa lưới",
                            Slug = "dua-luoi-1-kg-vhw1l0",
                            Status = true,
                            Stock = 100,
                            SupplierId = new Guid("5a0b659d-884a-446a-8b77-9b84ed6e2bf2"),
                            Unit = "Kg",
                            UpdatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 1.0
                        },
                        new
                        {
                            ProductId = new Guid("b39c0722-44aa-49e5-8ff9-b9ad9a9594fc"),
                            CategoryId = new Guid("2d482271-9605-4d43-9ca8-d479d6ef9687"),
                            CreatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Dưa gang tươi mát, ngọt lành, giàu vitamin và khoáng chất.</p>\r\n<ul>\r\n  <li>Giàu nước và vitamin C</li>\r\n  <li>Giúp giải nhiệt, tốt cho hệ tiêu hóa</li>\r\n  <li>Không hóa chất bảo quản</li>\r\n  <li>Thích hợp ăn trực tiếp và làm nước ép</li>\r\n  <li>Trồng tại các nông trại sạch</li>\r\n</ul>",
                            EntryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodName = "Winter melon",
                            Organic = true,
                            Origin = "Tỉnh Long An",
                            Price = 9000m,
                            ProductName = "Dưa gang",
                            Slug = "dua-gang-1-kg-t0055v",
                            Status = true,
                            Stock = 100,
                            SupplierId = new Guid("5a0b659d-884a-446a-8b77-9b84ed6e2bf2"),
                            Unit = "Kg",
                            UpdatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 1.0
                        });
                });

            modelBuilder.Entity("PureFood.Core.Domain.Content.Promotion", b =>
                {
                    b.Property<Guid>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedBy")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscountCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscountPercentage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PromotionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedBy")
                        .HasColumnType("datetime2");

                    b.HasKey("PromotionId");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("PureFood.Core.Domain.Content.Review", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("flag")
                        .HasColumnType("bit");

                    b.HasKey("ReviewId");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("PureFood.Core.Domain.Content.Supplier", b =>
                {
                    b.Property<Guid>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = new Guid("5a0b659d-884a-446a-8b77-9b84ed6e2bf2"),
                            Address = "Quận 9, Thành phố Hồ Chí Minh",
                            CreatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chúng tôi cung cấp rau củ quả sạch, tươi ngon từ nông trại đến bàn ăn, đảm bảo an toàn sức khỏe cho gia đình bạn.",
                            PhoneNumber = "0937056922",
                            SupplierName = "PureFood",
                            UpdatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SupplierId = new Guid("9b8bc0ba-e6af-4445-8509-390f404c1ea6"),
                            Address = "FPT Quận 9, Thành phố Hồ Chí Minh",
                            CreatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Moncati cung cấp rau củ quả sạch, tươi ngon từ nông trại địa phương, cam kết mang đến sản phẩm an toàn và chất lượng cho sức khỏe gia đình bạn.",
                            PhoneNumber = "0792766979",
                            SupplierName = "Moncati",
                            UpdatedAt = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PureFood.Core.Domain.Identity.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("322488f9-7aa9-49b0-b2b8-fd98b7b260fc"),
                            DisplayName = "Khách Hàng",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = new Guid("c0278115-8549-4fad-890a-44f8e8fcc022"),
                            DisplayName = "Quản Lý",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        });
                });

            modelBuilder.Entity("PureFood.Core.Domain.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<bool>("Supplier")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VipExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VipStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PureFood.Core.Domain.Content.Cart", b =>
                {
                    b.HasOne("PureFood.Core.Domain.Identity.AppUser", "User")
                        .WithOne("Cart")
                        .HasForeignKey("PureFood.Core.Domain.Content.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PureFood.Core.Domain.Content.CartItem", b =>
                {
                    b.HasOne("PureFood.Core.Domain.Content.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PureFood.Core.Domain.Content.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PureFood.Core.Domain.Content.Image", b =>
                {
                    b.HasOne("PureFood.Core.Domain.Content.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PureFood.Core.Domain.Content.OrderItem", b =>
                {
                    b.HasOne("PureFood.Core.Domain.Content.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PureFood.Core.Domain.Content.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PureFood.Core.Domain.Content.Product", b =>
                {
                    b.HasOne("PureFood.Core.Domain.Content.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PureFood.Core.Domain.Content.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("PureFood.Core.Domain.Content.Review", b =>
                {
                    b.HasOne("PureFood.Core.Domain.Content.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PureFood.Core.Domain.Content.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("PureFood.Core.Domain.Content.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PureFood.Core.Domain.Content.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("PureFood.Core.Domain.Content.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Images");

                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("PureFood.Core.Domain.Content.Supplier", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PureFood.Core.Domain.Identity.AppUser", b =>
                {
                    b.Navigation("Cart")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
